# Generated by Django 4.2.11 on 2025-12-28 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_producto_fecha_modificacion_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Vehículo/Patente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de Envío')),
                ('hora_estimada', models.TimeField(verbose_name='Hora Estimada de Entrega')),
                ('descripcion', models.TextField(verbose_name='Descripción del Envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('hora_real_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Entrega')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.chofer', verbose_name='Chofer Asignado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-fecha_envio', 'hora_estimada'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.envio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Envío',
                'verbose_name_plural': 'Detalles de Envíos',
            },
        ),
    ]
